<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\MAI.Domain\MAI.Domain.csproj" />
      <ProjectReference Include="..\MAI.DataAccessLayer\MAI.DataAccessLayer.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
