// <auto-generated />
using System;
using MAI.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MAI.DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921120000_OrgLevels")]
    partial class OrgLevels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MAI.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Result")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending()
                        .HasDatabaseName("IX_AuditLogs_Timestamp");

                    b.HasIndex("Username", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Username_Timestamp");

                    b.HasIndex("Action", "Result", "Timestamp")
                        .HasDatabaseName("IX_AuditLogs_Action_Result_Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChecksumSHA256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedStoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentVersions", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.FileTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowForward")
                        .HasColumnType("boolean");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("ChecksumSHA256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("CiphertextSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CryptoSuite")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("EncryptedKeyForSender")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<string>("EncryptedStoragePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("EncryptionIv")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderSignature")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_FileTransfers_ExpiresAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_FileTransfers_Status");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("UX_FileTransfers_StorageKey")
                        .HasFilter("\"StorageKey\" <> ''");

                    b.HasIndex("SenderId", "CreatedAt")
                        .HasDatabaseName("IX_FileTransfers_Sender_CreatedAt");

                    b.ToTable("FileTransfers", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.InternalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorOrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistributionMode")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IncludeSubunits")
                        .HasColumnType("boolean");

                    b.Property<string>("Number")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RepealedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RepealedById")
                        .HasColumnType("uuid");

                    b.Property<string>("RepealedReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("RequiresAcknowledgement")
                        .HasColumnType("boolean");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorOrgUnitId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_InternalDocuments_Status");

                    b.HasIndex("AuthorId", "CreatedAt")
                        .HasDatabaseName("IX_InternalDocuments_Author_CreatedAt");

                    b.ToTable("InternalDocuments", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.InternalDocumentRecipient", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FirstOpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId", "UserId");

                    b.HasIndex("OrgUnitId");

                    b.HasIndex("UserId", "AcknowledgedAt")
                        .HasDatabaseName("IX_InternalDocumentRecipients_User_Ack");

                    b.ToTable("InternalDocumentRecipients", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.InternalDocumentTarget", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentId", "Kind", "TargetId");

                    b.ToTable("InternalDocumentTargets", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.OrgLevel", b =>
                {
                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("Rank");

                    b.ToTable("OrgLevels", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.OrgUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HeadUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HeadUserId")
                        .IsUnique()
                        .HasDatabaseName("UX_OrgUnits_HeadUserId")
                        .HasFilter("\"HeadUserId\" IS NOT NULL");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_OrgUnits_ParentId");

                    b.ToTable("OrgUnits", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.TransferRecipient", b =>
                {
                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DownloadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedKeyForUser")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid?>("ForwardedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("SignatureValid")
                        .HasColumnType("boolean");

                    b.HasKey("TransferId", "UserId");

                    b.HasIndex("ForwardedById");

                    b.HasIndex("TransferId")
                        .HasDatabaseName("IX_TransferRecipients_TransferId");

                    b.HasIndex("UserId", "DownloadedAt")
                        .HasDatabaseName("IX_TransferRecipients_UserId_DownloadedAt");

                    b.ToTable("TransferRecipients", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CryptoSuite")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EncryptedPrivateBundle")
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("InvitationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InvitationTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("KeyDerivationIterations")
                        .HasColumnType("integer");

                    b.Property<string>("KeyDerivationSalt")
                        .HasColumnType("text");

                    b.Property<string>("KeyWrapIv")
                        .HasColumnType("text");

                    b.Property<DateTime?>("KeysCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFailedLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrgUnitId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublicKeyEncryption")
                        .HasColumnType("text");

                    b.Property<string>("PublicKeySigning")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("TwoFactorChallengeAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TwoFactorChallengeExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwoFactorChallengeHash")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("TwoFactorEnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("TwoFactorLastUsedStep")
                        .HasColumnType("bigint");

                    b.Property<string>("TwoFactorPendingSecret")
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorRecoveryCodeHashes")
                        .HasColumnType("text");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InvitationToken")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_InvitationToken")
                        .HasFilter("\"InvitationToken\" IS NOT NULL");

                    b.HasIndex("OrgUnitId")
                        .HasDatabaseName("IX_Users_OrgUnitId");

                    b.HasIndex("PasswordResetToken")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_PasswordResetToken")
                        .HasFilter("\"PasswordResetToken\" IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Username");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_UserSessions_ExpiresAt");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_UserSessions_RefreshTokenHash");

                    b.HasIndex("UserId", "RevokedAt")
                        .HasDatabaseName("IX_UserSessions_UserId_RevokedAt");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("MAI.Domain.Entities.Document", b =>
                {
                    b.HasOne("MAI.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("MAI.Domain.Entities.DocumentVersion", b =>
                {
                    b.HasOne("MAI.Domain.Entities.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MAI.Domain.Entities.FileTransfer", b =>
                {
                    b.HasOne("MAI.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("MAI.Domain.Entities.InternalDocument", b =>
                {
                    b.HasOne("MAI.Domain.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MAI.Domain.Entities.OrgUnit", "AuthorOrgUnit")
                        .WithMany()
                        .HasForeignKey("AuthorOrgUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("AuthorOrgUnit");
                });

            modelBuilder.Entity("MAI.Domain.Entities.InternalDocumentRecipient", b =>
                {
                    b.HasOne("MAI.Domain.Entities.InternalDocument", "Document")
                        .WithMany("Recipients")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAI.Domain.Entities.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("OrgUnit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAI.Domain.Entities.InternalDocumentTarget", b =>
                {
                    b.HasOne("MAI.Domain.Entities.InternalDocument", "Document")
                        .WithMany("Targets")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MAI.Domain.Entities.OrgUnit", b =>
                {
                    b.HasOne("MAI.Domain.Entities.User", "HeadUser")
                        .WithMany()
                        .HasForeignKey("HeadUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MAI.Domain.Entities.OrgUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("HeadUser");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MAI.Domain.Entities.TransferRecipient", b =>
                {
                    b.HasOne("MAI.Domain.Entities.User", "ForwardedBy")
                        .WithMany()
                        .HasForeignKey("ForwardedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MAI.Domain.Entities.FileTransfer", "Transfer")
                        .WithMany("Recipients")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ForwardedBy");

                    b.Navigation("Transfer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAI.Domain.Entities.User", b =>
                {
                    b.HasOne("MAI.Domain.Entities.OrgUnit", "OrgUnit")
                        .WithMany()
                        .HasForeignKey("OrgUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrgUnit");
                });

            modelBuilder.Entity("MAI.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("MAI.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MAI.Domain.Entities.Document", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MAI.Domain.Entities.FileTransfer", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("MAI.Domain.Entities.InternalDocument", b =>
                {
                    b.Navigation("Recipients");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("MAI.Domain.Entities.OrgUnit", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
